version: '3.8'

services:
  web:
    build: .
    command: gunicorn -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@localhost:5433/attendence_checker
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: attendence_checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
